services:
  - type: web
    name: myalgofax-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: SERVER_URL
        fromService:
          type: web
          name: myalgofax-api
          property: host